// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Carousel → images*
 */
export interface CarouselDocumentDataImagesItem {
	/**
	 * image field in *Carousel → images*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: carousel.images[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Content for Carousel documents
 */
interface CarouselDocumentData {
	/**
	 * images field in *Carousel*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: carousel.images[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	images: prismic.GroupField<Simplify<CarouselDocumentDataImagesItem>>;
}

/**
 * Carousel document from Prismic
 *
 * - **API ID**: `carousel`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CarouselDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<CarouselDocumentData>, "carousel", Lang>;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
	/**
	 * About us text field in *Footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.about_us_text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	about_us_text: prismic.KeyTextField;
	
	/**
	 * About us field in *Footer*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.about_us
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	about_us: prismic.LinkField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<FooterDocumentData>, "footer", Lang>;

/**
 * Item in *Navigation → Nav links dropdown*
 */
export interface NavigationDocumentDataNavLinksDropdownItem {
	/**
	 * nav link label field in *Navigation → Nav links dropdown*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.nav_links_dropdown[].nav_link_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	nav_link_label: prismic.KeyTextField;
	
	/**
	 * nav link url field in *Navigation → Nav links dropdown*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.nav_links_dropdown[].nav_link_url
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	nav_link_url: prismic.LinkField;
}

/**
 * Item in *Navigation → Nav links*
 */
export interface NavigationDocumentDataNavLinksItem {
	/**
	 * Link Label field in *Navigation → Nav links*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.nav_links[].link_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	link_label: prismic.KeyTextField;
	
	/**
	 * Link url field in *Navigation → Nav links*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.nav_links[].link_url
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link_url: prismic.LinkField;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
	/**
	 * logo field in *Navigation*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logo: prismic.ImageField<never>;
	
	/**
	 * Logo Heading field in *Navigation*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.logo_heading
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	logo_heading: prismic.KeyTextField;
	
	/**
	 * dropdown title field in *Navigation*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.dropdown_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	dropdown_title: prismic.KeyTextField;
	
	/**
	 * Nav links dropdown field in *Navigation*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.nav_links_dropdown[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	nav_links_dropdown: prismic.GroupField<Simplify<NavigationDocumentDataNavLinksDropdownItem>>;
	
	/**
	 * Nav links field in *Navigation*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.nav_links[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	nav_links: prismic.GroupField<Simplify<NavigationDocumentDataNavLinksItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<NavigationDocumentData>, "navigation", Lang>;

type ProductDocumentDataBodySlice = never

/**
 * Content for product documents
 */
interface ProductDocumentData {
	/**
	 * Name field in *product*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: Product name
	 * - **API ID Path**: product.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	name: prismic.TitleField;
	
	/**
	 * Description field in *product*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Product Description
	 * - **API ID Path**: product.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * Price field in *product*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.price
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	price: prismic.NumberField;
	
	/**
	 * rating field in *product*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.rating
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	rating: prismic.NumberField;
	
	/**
	 * Category field in *product*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.category
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	category: prismic.SelectField<"Shirt" | "Pant" | "Accessories">;
	
	/**
	 * Product image field in *product*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.product_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	product_image: prismic.ImageField<never>;
	
	/**
	 * Slice zone field in *product*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.body[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	body: prismic.SliceZone<ProductDocumentDataBodySlice>;
}

/**
 * product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<ProductDocumentData>, "product", Lang>;

export type AllDocumentTypes = CarouselDocument | FooterDocument | NavigationDocument | ProductDocument;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			CarouselDocument,
			CarouselDocumentData,
			CarouselDocumentDataImagesItem,
			FooterDocument,
			FooterDocumentData,
			NavigationDocument,
			NavigationDocumentData,
			NavigationDocumentDataNavLinksDropdownItem,
			NavigationDocumentDataNavLinksItem,
			ProductDocument,
			ProductDocumentData,
			ProductDocumentDataBodySlice,
			AllDocumentTypes
		}
	}
}