// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Carousel → images*
 */
export interface CarouselDocumentDataImagesItem {
	/**
	 * image field in *Carousel → images*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: carousel.images[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Content for Carousel documents
 */
interface CarouselDocumentData {
	/**
	 * images field in *Carousel*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: carousel.images[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	images: prismic.GroupField<Simplify<CarouselDocumentDataImagesItem>>;
}

/**
 * Carousel document from Prismic
 *
 * - **API ID**: `carousel`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CarouselDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<CarouselDocumentData>, "carousel", Lang>;

/**
 * Item in *Homepage → images*
 */
export interface HomepageDocumentDataImagesItem {
	/**
	 * image field in *Homepage → images*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.images[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
	/**
	 * Button text field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.button_text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text: prismic.KeyTextField;
	
	/**
	 * Dialog Title field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.dialog_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	dialog_title: prismic.KeyTextField;
	
	/**
	 * Dialog content field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.dialog_content
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	dialog_content: prismic.KeyTextField;
	
	/**
	 * close button field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.close_button
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	close_button: prismic.KeyTextField;
	
	/**
	 * images field in *Homepage*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.images[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	images: prismic.GroupField<Simplify<HomepageDocumentDataImagesItem>>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;

/**
 * Item in *Navigation → Nav links dropdown*
 */
export interface NavigationDocumentDataNavLinksDropdownItem {
	/**
	 * nav link label field in *Navigation → Nav links dropdown*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.nav_links_dropdown[].nav_link_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	nav_link_label: prismic.KeyTextField;
	
	/**
	 * nav link url field in *Navigation → Nav links dropdown*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.nav_links_dropdown[].nav_link_url
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	nav_link_url: prismic.LinkField;
}

/**
 * Item in *Navigation → Nav links*
 */
export interface NavigationDocumentDataNavLinksItem {
	/**
	 * Link Label field in *Navigation → Nav links*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.nav_links[].link_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	link_label: prismic.KeyTextField;
	
	/**
	 * Link url field in *Navigation → Nav links*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.nav_links[].link_url
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link_url: prismic.LinkField;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
	/**
	 * logo field in *Navigation*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logo: prismic.ImageField<never>;
	
	/**
	 * Logo Heading field in *Navigation*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.logo_heading
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	logo_heading: prismic.KeyTextField;
	
	/**
	 * dropdown title field in *Navigation*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.dropdown_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	dropdown_title: prismic.KeyTextField;
	
	/**
	 * Nav links dropdown field in *Navigation*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.nav_links_dropdown[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	nav_links_dropdown: prismic.GroupField<Simplify<NavigationDocumentDataNavLinksDropdownItem>>;
	
	/**
	 * Nav links field in *Navigation*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.nav_links[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	nav_links: prismic.GroupField<Simplify<NavigationDocumentDataNavLinksItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<NavigationDocumentData>, "navigation", Lang>;

type ProductDocumentDataBodySlice = never

/**
 * Content for product documents
 */
interface ProductDocumentData {
	/**
	 * Name field in *product*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: Product name
	 * - **API ID Path**: product.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	name: prismic.TitleField;
	
	/**
	 * Description field in *product*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Product Description
	 * - **API ID Path**: product.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * Price field in *product*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.price
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	price: prismic.NumberField;
	
	/**
	 * rating field in *product*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.rating
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	rating: prismic.NumberField;
	
	/**
	 * Category field in *product*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.category
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	category: prismic.SelectField<"Shirt" | "Pant" | "Accessories">;
	
	/**
	 * Product image field in *product*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.product_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	product_image: prismic.ImageField<never>;
	
	/**
	 * Slice zone field in *product*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.body[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	body: prismic.SliceZone<ProductDocumentDataBodySlice>;
}

/**
 * product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<ProductDocumentData>, "product", Lang>;

export type AllDocumentTypes = CarouselDocument | HomepageDocument | NavigationDocument | ProductDocument;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			CarouselDocument,
			CarouselDocumentData,
			CarouselDocumentDataImagesItem,
			HomepageDocument,
			HomepageDocumentData,
			HomepageDocumentDataImagesItem,
			NavigationDocument,
			NavigationDocumentData,
			NavigationDocumentDataNavLinksDropdownItem,
			NavigationDocumentDataNavLinksItem,
			ProductDocument,
			ProductDocumentData,
			ProductDocumentDataBodySlice,
			AllDocumentTypes
		}
	}
}